
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/PROJECT_ID/my-repo/my-app:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/PROJECT_ID/my-repo/my-app:$SHORT_SHA'
      ]

  # Step 3: Authenticate to GKE and set up kubectl
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'container',
        'clusters',
        'get-credentials',
        'CLUSTER_NAME',
        '--zone',
        'COMPUTE_ZONE',
        '--project',
        'PROJECT_ID'
      ]

  # Step 4: Update deployment in Kubernetes cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        'image',
        'deployment/my-deployment',
        'my-container=us-central1-docker.pkg.dev/PROJECT_ID/my-repo/my-app:$SHORT_SHA'
      ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=CLUSTER_NAME'

images:
  - 'us-central1-docker.pkg.dev/PROJECT_ID/my-repo/my-app:$SHORT_SHA'
