apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2  # Adjust as needed (number of pods)
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: asia-southeast1-docker.pkg.dev/western-emitter-461905-e7/cicd-testing/my-app:latest  # Update to your image path
          ports:
            - containerPort: 8080
