steps:
  # Step 1: Get the latest Git tag (this will be your version number)
  - name: 'alpine'
    id: 'get_git_tag'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        VERSION=$(git describe --tags --abbrev=0)
        echo "Using Git tag version: $VERSION"
        echo $VERSION > /workspace/version.txt  # Optionally save the version for later steps
        echo $VERSION > /workspace/_VERSION  # Set _VERSION for substitution

  # Step 2: Build Docker image with the Git tag as the version
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/western-emitter-461905-e7/cicd-testing/my-app:${_VERSION}',  # Use custom version as the tag
        '.'
      ]

  # Step 3: Push Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast1-docker.pkg.dev/western-emitter-461905-e7/cicd-testing/my-app:${_VERSION}'  # Push with the custom version tag
      ]

images:
  - 'asia-southeast1-docker.pkg.dev/western-emitter-461905-e7/cicd-testing/my-app:${_VERSION}'

options:
  logging: CLOUD_LOGGING_ONLY  # Logs will be stored in Cloud Logging
