substitutions:
  _VERSION: '0.0.1'  # Define the starting version or dynamic version from Git tag

steps:
  # Step 1: Get the latest Git tag (this will be your version number)
  - name: 'alpine'
    id: 'get_git_tag'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        VERSION=$(git describe --tags --abbrev=0)  # Get the latest git tag (version)
        echo "Using Git tag version: $VERSION"
        echo $VERSION > /workspace/version.txt  # Save the version for later use
        echo $VERSION > /workspace/_VERSION  # Set _VERSION substitution dynamically

  # Step 2: Build Docker image with the Git tag as the version
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/western-emitter-461905-e7/cicd-testing/my-app:${_VERSION}',  # Tag the image with the Git version
        '.'
      ]

  # Step 3: Push Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast1-docker.pkg.dev/western-emitter-461905-e7/cicd-testing/my-app:${_VERSION}'  # Push with the Git version tag
      ]

images:
  - 'asia-southeast1-docker.pkg.dev/western-emitter-461905-e7/cicd-testing/my-app:${_VERSION}'

options:
  logging: CLOUD_LOGGING_ONLY  # Logs will be stored in Cloud Logging
